services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.2.1
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:9.2.1
    networks:
      - elk

  # web.api:
  #   image: ${DOCKER_REGISTRY-}webapi
  #   build:
  #     context: .
  #     dockerfile: Web.Api/Dockerfile
  #   networks:
  #     - elk

networks:
  elk:
    driver: bridge
